### ISSUE TITLE
Avoid VCEP sheet refresh breakage on clinvar release updates

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/clinvar-ingest-reports#87]
Discussed on Slack Feb 23 2024 after Alerts and Priorities tabs weren't populating with new ClinVar release

Larry's response: I can attest that the VCEP sheets are now returning the alerts and priorities as expected. I think it would be smart if you would add a ticket assigned to me titled "Avoid VCEP sheet refresh breakage on clinvar release updates" which is something we can discuss and determine how to best manage this. I really want to avoid or at least massively reduce any windows where the VCEP users would be turned off or frustrated by events like this. I sort of lost track of the fact that there was this window and started the process and walked away before completing it not realizing it was going to cause any users to hit this issue.

**Comment by larrybabb** [comment]
A month ago or less I did some major updates to how the data is being retrieved which introduced a  new resource that requires additional access (the ClinVar Report BQ Support Tables google sheet in the B/G shared google drive).  This introduced the breaking change since the "Refresh" function now needs the ability for the user to read that sheet.  So, to try to make things simpler all around, I think we should simply add any google account users that need to work with any of our clinvar-based google sheets to the clingen-data-read@broadinstitute.org google group.  I've assigned this google group to the ClinVar Report BQ Support Tables google sheet in the B/G shared google drive with View permissions and we should make sure this google group has editor permissions on the VCEP Report shared drive in the ClinGen Site shared google drive (versus individually adding accounts to that folder).  And we can stop adding folks that do not need the chrome extension access to the Oauth Consent list of test users.

**Comment by larrybabb** [comment]
Due to the fact that we are short on resources to do a full scale analysis and resolution for this and because this hasn't happened since 2/23/2024. I am going to close this ticket and we can wait until this wheel squeaks again before determining if material resources are worth investing in a fix.
